# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cbnu_msgs/AnObjectData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class AnObjectData(genpy.Message):
  _md5sum = "f64d9f4ae123fec27fe26952d0c80dfc"
  _type = "cbnu_msgs/AnObjectData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string object_type
float32 rel_pos_x
float32 rel_pos_y
float32 global_pos_lat
float32 global_pos_lon
"""
  __slots__ = ['object_type','rel_pos_x','rel_pos_y','global_pos_lat','global_pos_lon']
  _slot_types = ['string','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       object_type,rel_pos_x,rel_pos_y,global_pos_lat,global_pos_lon

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AnObjectData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.object_type is None:
        self.object_type = ''
      if self.rel_pos_x is None:
        self.rel_pos_x = 0.
      if self.rel_pos_y is None:
        self.rel_pos_y = 0.
      if self.global_pos_lat is None:
        self.global_pos_lat = 0.
      if self.global_pos_lon is None:
        self.global_pos_lon = 0.
    else:
      self.object_type = ''
      self.rel_pos_x = 0.
      self.rel_pos_y = 0.
      self.global_pos_lat = 0.
      self.global_pos_lon = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.object_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4f().pack(_x.rel_pos_x, _x.rel_pos_y, _x.global_pos_lat, _x.global_pos_lon))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_type = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.rel_pos_x, _x.rel_pos_y, _x.global_pos_lat, _x.global_pos_lon,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.object_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4f().pack(_x.rel_pos_x, _x.rel_pos_y, _x.global_pos_lat, _x.global_pos_lon))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_type = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.rel_pos_x, _x.rel_pos_y, _x.global_pos_lat, _x.global_pos_lon,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
