# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cbnu_msgs/MultiScenarioLoad.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MultiScenarioLoad(genpy.Message):
  _md5sum = "72663bbaba4c22d9e77ddf06c9dac39c"
  _type = "cbnu_msgs/MultiScenarioLoad"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string[] file_name
bool[] load_ego_vehicle_data
bool[] load_surrounding_vehicle_data
bool[] load_pedestrian_data
bool[] load_object_data
"""
  __slots__ = ['file_name','load_ego_vehicle_data','load_surrounding_vehicle_data','load_pedestrian_data','load_object_data']
  _slot_types = ['string[]','bool[]','bool[]','bool[]','bool[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       file_name,load_ego_vehicle_data,load_surrounding_vehicle_data,load_pedestrian_data,load_object_data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MultiScenarioLoad, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.file_name is None:
        self.file_name = []
      if self.load_ego_vehicle_data is None:
        self.load_ego_vehicle_data = []
      if self.load_surrounding_vehicle_data is None:
        self.load_surrounding_vehicle_data = []
      if self.load_pedestrian_data is None:
        self.load_pedestrian_data = []
      if self.load_object_data is None:
        self.load_object_data = []
    else:
      self.file_name = []
      self.load_ego_vehicle_data = []
      self.load_surrounding_vehicle_data = []
      self.load_pedestrian_data = []
      self.load_object_data = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.file_name)
      buff.write(_struct_I.pack(length))
      for val1 in self.file_name:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      length = len(self.load_ego_vehicle_data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.Struct(pattern).pack(*self.load_ego_vehicle_data))
      length = len(self.load_surrounding_vehicle_data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.Struct(pattern).pack(*self.load_surrounding_vehicle_data))
      length = len(self.load_pedestrian_data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.Struct(pattern).pack(*self.load_pedestrian_data))
      length = len(self.load_object_data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.Struct(pattern).pack(*self.load_object_data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.file_name = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.file_name.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.load_ego_vehicle_data = s.unpack(str[start:end])
      self.load_ego_vehicle_data = list(map(bool, self.load_ego_vehicle_data))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.load_surrounding_vehicle_data = s.unpack(str[start:end])
      self.load_surrounding_vehicle_data = list(map(bool, self.load_surrounding_vehicle_data))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.load_pedestrian_data = s.unpack(str[start:end])
      self.load_pedestrian_data = list(map(bool, self.load_pedestrian_data))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.load_object_data = s.unpack(str[start:end])
      self.load_object_data = list(map(bool, self.load_object_data))
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.file_name)
      buff.write(_struct_I.pack(length))
      for val1 in self.file_name:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      length = len(self.load_ego_vehicle_data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.load_ego_vehicle_data.tostring())
      length = len(self.load_surrounding_vehicle_data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.load_surrounding_vehicle_data.tostring())
      length = len(self.load_pedestrian_data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.load_pedestrian_data.tostring())
      length = len(self.load_object_data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.load_object_data.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.file_name = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.file_name.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.load_ego_vehicle_data = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.load_ego_vehicle_data = list(map(bool, self.load_ego_vehicle_data))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.load_surrounding_vehicle_data = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.load_surrounding_vehicle_data = list(map(bool, self.load_surrounding_vehicle_data))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.load_pedestrian_data = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.load_pedestrian_data = list(map(bool, self.load_pedestrian_data))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.load_object_data = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.load_object_data = list(map(bool, self.load_object_data))
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
