(cl:in-package cbnu_msgs-msg)
(cl:export '(NED_LATITUDE-VAL
          NED_LATITUDE
          NED_LONGITUDE-VAL
          NED_LONGITUDE
          NED_HEADING-VAL
          NED_HEADING
          SPEED-VAL
          SPEED
          STEERING_ANGLE-VAL
          STEERING_ANGLE
          STEERING_ANGULAR_VELOCITY-VAL
          STEERING_ANGULAR_VELOCITY
          WHEEL_VELOCITY_FL-VAL
          WHEEL_VELOCITY_FL
          WHEEL_VELOCITY_FR-VAL
          WHEEL_VELOCITY_FR
          WHEEL_VELOCITY_RL-VAL
          WHEEL_VELOCITY_RL
          WHEEL_VELOCITY_RR-VAL
          WHEEL_VELOCITY_RR
          WHEEL_SIZE_FL-VAL
          WHEEL_SIZE_FL
          WHEEL_SIZE_FR-VAL
          WHEEL_SIZE_FR
          WHEEL_SIZE_RL-VAL
          WHEEL_SIZE_RL
          WHEEL_SIZE_RR-VAL
          WHEEL_SIZE_RR
          ACCELERATION_LEFT-VAL
          ACCELERATION_LEFT
          ACCELERATION_FORWARD-VAL
          ACCELERATION_FORWARD
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          WHEEL_BASE-VAL
          WHEEL_BASE
          CURB_WEIGHT-VAL
          CURB_WEIGHT
))